### ISSUE TITLE
Input file example

### ISSUE THREAD

**Issue by aminnairi** [Fabrice-Heuvrard/Convert-FEC-to-JSON#1]
It would be nice to have an example input file for several reasons:
- Allow non-accounting experts to see the format expected by this script
- Allow contributors to write tests since this project does not test its implementation and it could break things up quickly and may introduce regression whenever this script is enhanced
- This would improve the quality and reinsurance of this script

Once you provide us with an example, we could then:
- Help with providing some unit tests
- Create an automation using GitHub Actions' Workflows

Great project, thanks for sharing with the open-source community!

**Comment by Fabrice-Heuvrard** [comment]
En anglais :
I plan to add a FEC file to my project that contains an example of each of these types of accounting entries: a purchase with VAT, a sale with VAT, and a supplier payment in the bank with reconciliation of the payment with its invoice, including a lettering code. This will serve as a practical example for users of my script.



En français :
Je prévois d'ajouter à mon projet un fichier FEC contenant un exemple de chacun de ces types d'écritures comptables : un achat avec TVA, une vente avec TVA, et un paiement fournisseur en banque avec rapprochement du paiement avec sa facture, incluant un code de lettrage. Ceci servira d'exemple pratique pour les utilisateurs de mon script.
